---
description: "#{repo}"
builds:
- platform: "debian"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_debian_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
- platform: "centos"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_centos_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'rhel'"
- platform: "alpine"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_alpine_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'alpine'"